name: Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: go test -v -race